### PR TITLE
AnyKey

### PR DESCRIPTION
**Pull request by samuelcolvin**
Suggested implementation of `AnyKey` class to allow all "other" key - values to be validated.

Adding `AnyKey` is equivalent of `.allow_extra("*")` except those extra values are validated.

If you're happy with this I'll add documentation etc.

### CODE REVIEW

**Comment by asvetlov** [comment]
Looks good.
@Deepwalker ?

**Comment by Deepwalker** [comment]
Cool idea to rework ignore/extra thing. But I'm not sure that this implementation did it right.
1. keys can touch several mapping entries, so you cant use key.name due its implementation detail.
2. you can use any callable as a key, and this callables does not have any `.name` fields.

I cant provide right solution now, but will think about it. Now I see that this is really a problem with extra thing. Maybe set special `extra` trafaret?

**Comment by samuelcolvin** [comment]
I'll make some changes that allow for keys without "name".

I'm a bit confused by what you mean by

> Now I see that this is really a problem with extra thing. Maybe set special extra trafaret?

Could you explain a little more?

**Comment by Deepwalker** [comment]
I mean situation when you have not trafaret for extra keys is not good and really is problem. Never thought about it before your pullreq.
About second part — we can implement `allow_extra(t.String)`

**Comment by Deepwalker** [comment]
Check 0.7.4 and new allow_extra(trafaret=t.Int) arg.

**Comment by samuelcolvin** [comment]
i guess 2aa39f1a9277fc83055a9826cea7df69123ebb88 replaces this.

**Pull request closed without merging**
